[package]
name = "survey"
version = "0.1.0"
authors = ["C.Solovev <constantine.solovev@gmail.com>"]
edition = "2018"

[dependencies]
actix-web = "3"
actix-cors = "0.5.4"
serde = "1"
env_logger = "0.8"